# Generated by Django 6.0.1 on 2026-01-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="weathercache",
            name="city_country_idx",
        ),
        migrations.AlterUniqueTogether(
            name="weathercache",
            unique_together={("city", "state", "country")},
        ),
        migrations.AddIndex(
            model_name="weathercache",
            index=models.Index(
                fields=["city", "state", "country"], name="city_country_idx"
            ),
        ),
    ]
