# Generated by Django 6.0.1 on 2026-01-21 04:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_weathercache_city_country_idx_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="weathercache",
            new_name="weather_cache_city_state_country_idx",
            old_name="city_country_idx",
        ),
        migrations.AlterUniqueTogether(
            name="searchhistory",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="weathercache",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="searchhistory",
            name="weather_cache",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="searches",
                to="api.weathercache",
            ),
        ),
        migrations.AlterField(
            model_name="searchhistory",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                max_length=15,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format '+999999999'.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
                verbose_name="Phone Number",
            ),
        ),
        migrations.AlterField(
            model_name="weathercache",
            name="country",
            field=models.CharField(
                max_length=100,
                validators=[django.core.validators.MinLengthValidator(2)],
            ),
        ),
        migrations.AlterField(
            model_name="weathercache",
            name="data",
            field=models.JSONField(help_text="Raw weather provider response payload"),
        ),
        migrations.AddIndex(
            model_name="searchhistory",
            index=models.Index(fields=["user"], name="search_history_user_idx"),
        ),
        migrations.AddConstraint(
            model_name="weathercache",
            constraint=models.UniqueConstraint(
                fields=("city", "state", "country"),
                name="unique_weather_cache_location",
            ),
        ),
        migrations.RemoveField(
            model_name="searchhistory",
            name="response_data",
        ),
    ]
