# Generated by Django 6.0.1 on 2026-01-21 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "api",
            "0003_rename_city_country_idx_weather_cache_city_state_country_idx_and_more",
        ),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="weathercache",
            new_name="weathercache_index",
            old_name="weather_cache_city_state_country_idx",
        ),
        migrations.AlterField(
            model_name="searchhistory",
            name="weather_cache",
            field=models.JSONField(
                blank=True, help_text="Weather data payload", null=True
            ),
        ),
    ]
